sudo: required
language: generic
dist: xenial

matrix:
  include:
  - name: "Kinetic"
    env: BEFORE_SCRIPT="pip install pip --upgrade" ROS_DISTRO=kinetic

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
